aider: Updated URLs for adding tech, site, and note in AdminPage.js to fix 404 error.
# Aider chat conversation:

USER: AdminPage.js:11

        POST http://100.106.210.42:3000/add-tech 404 (Not Found)
dispatchXhrRequest @ xhr.js:188
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
_request @ Axios.js:173
request @ Axios.js:40
httpMethod @ Axios.js:212
wrap @ bind.js:5
handleAddTech @ AdminPage.js:11
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26179
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 22 more frames
Show less
AdminPage.js:20  Error adding tech: AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}

ASSISTANT: The error indicates that the POST request to add a tech is failing with a 404 status code, which means the endpoint is not found. This could be due to the incorrect URL being used in the request.

Let's update the URL in the `AdminPage.js` file to match the correct endpoint defined in `src/server.js`.

Here are the changes:

src/components/AdminPage.js
```javascript
<<<<<<< SEARCH
      const response = await axios.post('/add-tech', { name: newTech });
=======
      const response = await axios.post('http://localhost:3000/add-tech', { name: newTech });
>>>>>>> REPLACE
```

Similarly, we need to update the URLs for adding a site and a note:

src/components/AdminPage.js
```javascript
<<<<<<< SEARCH
      const response = await axios.post('/add-site', { name: newSite });
=======
      const response = await axios.post('http://localhost:3000/add-site', { name: newSite });
>>>>>>> REPLACE
```

src/components/AdminPage.js
```javascript
<<<<<<< SEARCH
      const response = await axios.post('/add-note', { name: newNote });
=======
      const response = await axios.post('http://localhost:3000/add-note', { name: newNote });
>>>>>>> REPLACE
```